# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import user_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0033_knackuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knackuser',
            name='about_me',
            field=models.TextField(default="I'm a senior here at Harvard University and study bio-engineering. I love writing and reading. Contact me anytime if you need help."),
        ),
        migrations.AlterField(
            model_name='knackuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('MM', 'Male'), ('FF', 'Female'), ('TT', 'Transgender'), ('II', 'Intersex'), ('GN', 'Gender Neutral'), ('GQ', 'Genderqueer'), ('CC', 'Cisgender'), ('BB', 'Bigender'), ('PP', 'Pangender')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='knackuser',
            name='payment_paypal',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='knackuser',
            name='payment_venmo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='knackuser',
            name='reasons',
            field=user_auth.models.ListField(default=["I'm an awesome knacker", 'Who absolutely loves what I do', "I'm fun, fair and honest", "I'll do a great job everytime", "you'll really love your knack"]),
        ),
    ]
