# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0034_auto_20160408_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='googleplus',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
