# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0036_auto_20160412_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knackuser',
            name='public_profile_url',
        ),
    ]
