# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0037_remove_knackuser_public_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knackuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
