# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0038_auto_20160430_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='knackuser',
            name='connections',
            field=models.ManyToManyField(db_index=True, related_name='connected_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
