# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0039_knackuser_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='knackuser',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='online status'),
        ),
    ]
