# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0040_knackuser_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knackuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Trans', 'Trans'), ('Andro', 'Andro'), ('Exploring', 'Exploring'), ('Alien', 'Alien'), ('No Gender', 'No Gender')], max_length=30, null=True),
        ),
    ]
