# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0041_auto_20160507_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='knackuser',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address for notifications'),
        ),
    ]
