# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knacks', '0011_auto_20160408_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knack',
            name='photo0',
            field=models.ImageField(blank=True, null=True, upload_to='knacks/'),
        ),
        migrations.AlterField(
            model_name='knack',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='knacks/'),
        ),
        migrations.AlterField(
            model_name='knack',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='knacks/'),
        ),
        migrations.AlterField(
            model_name='knack',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='knacks/'),
        ),
        migrations.AlterField(
            model_name='knack',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='knacks/'),
        ),
    ]
