# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20160327_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='miles',
            field=models.CharField(choices=[('5 miles', '5 miles'), ('10 miles', '10 miles'), ('20 miles', '20 miles'), ('50+ miles', '50+ miles'), ('On Campus', 'On Campus')], default='On Campus', max_length=255, verbose_name='How far?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo0',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo4',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='schedule',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="What's your schedule like?"),
        ),
        migrations.AlterField(
            model_name='item',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Anonymous Username'),
        ),
        migrations.AlterField(
            model_name='item',
            name='willing_to_travel',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Are you willing to travel?'),
        ),
    ]
