# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20160408_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo0',
            field=models.ImageField(blank=True, null=True, upload_to='knacks/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='knacks/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='knacks/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='knacks/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='knacks/'),
        ),
    ]
